# Generated by Django 3.2.5 on 2023-03-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='userId',
            new_name='user',
        ),
    ]
