# Generated by Django 3.2.5 on 2023-03-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
