# Generated by Django 3.2.5 on 2023-03-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230309_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='comments',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rating_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
