# Generated by Django 3.2.5 on 2023-03-10 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230310_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='rating_score',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
