# Generated by Django 3.2.5 on 2023-03-10 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_inventory_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='comments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='rating_score',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
