# Generated by Django 3.2.5 on 2023-03-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230310_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_buying',
            field=models.BooleanField(default=False),
        ),
    ]
