# Generated by Django 3.2.5 on 2023-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_inventory_is_in_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='origin',
        ),
        migrations.AddField(
            model_name='item',
            name='instruction',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
