# Generated by Django 3.2.5 on 2023-03-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_inventory_is_in_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bought_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
