# Generated by Django 3.2.5 on 2023-03-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_inventory_bought_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bought_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
