# Generated by Django 3.2.5 on 2023-03-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_inventory_bought_quantity'),
        ('main', '0013_auto_20230320_2137'),
    ]

    operations = [
    ]
