# Generated by Django 3.2.5 on 2023-03-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20230320_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='bought_quantity',
        ),
    ]
